unified_mode     'true'
name             'rb-postfix'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-postfix'
version          '0.0.6'
