unified_mode     'true'
name             'rb-postfix'
maintainer       'David Vanhoucke'
maintainer_email 'dvanhoucke@redborder.com'
license          'All rights reserved'
description      'Installs/Configures cookbook-rb-postfix'
version          '0.0.2'
